- main.go
- migrate/migrate.go
- migrate/migrate_test.go
- migrate/testdata/noforward/001_create_no_forward.sql
Hey, I am not sure if this is something useful in general, we have found this to blow in our faces when we misplaced migration lines.
The idea is to be able to pass a flag on migration to have them blow in our faces if a forward step is suspiciously empty (Which we assume is not a very common use case)
> Fail when a forward migration lacks SQL

- migrate/migrate.go
- migrate/migrate_test.go
The way we run tests involves creating a transaction, running migrations, using save points during the test, then rolling back to leave the database empty again. This works really nicely except that if the version table does not exist yet, `migrate.NewMigratorEx` fails because the call to `Migrator.GetCurrentVersion` with a missing table aborts the transaction.
We currently work around this by duplicating `Migrator.ensureSchemaVersionTableExists` with this patch applied and calling that before `migrate.NewMigratorEx`.
This PR is in case you're interested in supporting this use case in tern itself. It replaces the method of checking for a missing version table with a query against the `pg_catalog.pg_tables` view. This leaves open transactions active, even if the version table does not …
> Allow migrations inside of a transaction

- README.markdown
- ssh_tunnel.go
Running `tern` with `--ssh-host`/`--ssh-user` but no SSH agent would panic due to passing in a nil `ssh.AuthMethod`:
```
tern migrate --database xxx --user xxx --ssh-host xxx --ssh-user xxx --migrations xxx/xxx --destination x
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x83f215]
goroutine 1 [running]:
golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc0000e6b00, 0xc0000b7ee0, 0x0, 0xa)
/home/miles/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83/ssh/client_auth.go:65 +0x435
golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc0000e6b00, 0xc00002df88, 0x8, 0xc0000b7ee0, 0x0, 0x0)
/home/miles/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83/ssh/client.go:1 …
```
> offer default SSH keyfile if not using agent

- README.markdown
This change updates the README installation section, to use `go install` for newer Go versions (>= 1.17). Both the old `go get` method and new method remain described to support users of the older Go versions.
As of Go 1.17, the use of `go get` for installing executables is [deprecated]( https://golang.org/doc/go-get-install-deprecation). And will be disabled from Go 1.18. As per message on command line:
```
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
> update installation section for newer Go versions

- go.mod
- go.sum
- main.go
- tern_test.go
- testdata/tern-conn-string.conf
This property is lenient i.e., it does not throw error
if values for both "connection string" and "host/port/.." are
provided. In this case, the individual properties will
override the correspoding part in the "connection string".
Usage:
- In tern.conf file:
```
[database]
conn_string = <URI or DSN>
```
- Through CLI:
`tern [command] --conn-string <URI or DSN>`
> Add "connection string" property for pg connection

- main.go
- migrate/migrate.go
Simply put, when using `tern/migrate` to run migrations, if a migration fails the error is returned and the PgError message is printed to the user. It would be useful to show to the user which of their migration files caused the error.
Intended use:
```go
if err := m.Migrate(ctx); err != nil {
var migrationErr migrate.MigrationPgError
if errors.As(err, &migrationErr) {
fmt.Fprintf(os.Stderr, "failed to perform migration(s): %s: %v\n", migrationErr.Filename, migrationErr.PgError)
os.Exit(1)  
}
// handle error
}
```
> add Filename to MigrationPgError

- migrate/code.go
- migrate/migrate.go
Exports the `DefaultMigratorFS`, see: https://github.com/jackc/tern/issues/36#issuecomment-1109061622
> Export DefaultMigratorFS

- migrate/migrate.go
- migrate/migrate_test.go
Implemented following the discussion at #62.
The underlying issue was that `FindMigrationsEx` would not work if files in migrations directory were not properly sorted (say, 1 through 10 without padding 0s).
This PR fixes that. The function still identifies if migrations are missing/repeated. It also returns the paths sorted in the expected order (regardless of padding 0s).
> Fix unsorted migrations bug

- go.mod
Hey,
appreciate the tag, however, it does not work due to missing module. Go errors with:
```
lzap@mone provisioning-backend % go mod tidy
go: downloading github.com/jackc/tern/v2 v2.0.0-beta.1
github.com/RHEnVision/provisioning-backend/internal/db imports
github.com/jackc/tern/v2/migrate: go.mod has non-.../v2 module path "github.com/jackc/tern" (and .../v2/go.mod does not exist) at revision v2.0.0-beta.1
```
> Change module name

- .github/workflows/release.yaml
- .goreleaser.yaml
This adds some CI spec files to build-release an amd64 linux bin on every `v*` tag push. No additional configuration needed, it will run on the next such tag push.
Closes:
- #70 
- #56
> ci: add build release feature

- main.go
I was accidentally using loadConfigAndConnectToDB instead of just LoadConfig. The connection is not needed for just printing out the connstring. oops.
> remove unnedded connection to db

- migrate/migrate.go
If a migration was missing and the directory contained only valid migration files, `FindMigrations` would panic with an index out of range error instead of returning an error indicating a missing migration.
I think this was missed in #65 because the test data included a non-migration file that added an extra element to the `foundMigrations` slice.
> Fix FindMigrations panic with missing migrations

- main.go
If the sslmode was blank then some of the fallback config was not being set properly. This was because blank is treated as "prefer" by pgx (which follows libpq's behavior). But tern parsing parsing the config in several places and then trying to fix the fallback config. It missed the default "prefer" case.
The solution was to avoid the multiple parsing and fallback config logic entirely. Instead, we set the PG* environment variables from the CLI options and config file before parsing the conn string.
https://github.com/jackc/tern/issues/38
> Fix fallback config confusion

- README.markdown
- go.mod
- go.sum
- main.go
- ssh_tunnel.go
- win_ssh_agent_other.go
- win_ssh_agent_windows.go
I use tern on windows and I am using the native windows ssh agent implementation.
This implementation does not expose the ssh agent on a unix socket, but on a pipe. 
This PR adds another authentication method for ssh tunneling if it detects a native windows pipe.
This adds a direct dependency to `github.com/Microsoft/go-winio` (MIT License)
> Enhance ssh agent support (windows pipe and other id_* key files)

- migrate/migrate.go
fixes #111
Do not use `fs.Join(...)` as argument to `fs.Glob(..)`, as it fails on Wiindows.
`fs.Glob()` expects a pattern like `fs.Match()`. On Windows `fs.Join("*", "*.sql")` will produce `"*\\*.sql"` which is not what one wants (` "*/*.sql"`). On Linux `fs.Join("*", "*.sql")` results in`"*/*.sql"` which is a vaild pattern.
> Fix template lookup on Windows

- .gitignore
- .goreleaser.yaml
Added the new files to the docker build
Added window as build target
@jackc Late, but here is a (hoefully) fixed go-releaser config
> Fix go-releaser and build for windows too

- .goreleaser.yaml
I added the forgotten file. Having `-push` commented, it builds locally without error.
Hope it works this time.
> Add forgotten file

- README.markdown
Realized that I forgot to update the README after the last change on https://github.com/jackc/tern/pull/122.
> README: library sample code should use *pgx.Conn, not pgx.Tx

- migrate/migrate.go
- migrate/migrate_test.go
Caveat: using os.DirFS we lose the original path. I've tried to see if we could recover it somehow, but nope...
> Fix migrate.LoadMigrations panic (nil pointer dereference) when directory doesn't exist

- go.mod
https://nvd.nist.gov/vuln/detail/CVE-2025-22869
> Resolve CVE-2025-22869 (Crypto-SSH)
